### PR TITLE
fix: failing `cargo clippy` check in CI

### LINKED ISSUE #644: `CI / Clippy CI (push) Failing after 1m` on main branch

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #644.

### CODE REVIEW

File: fyrox-core-derive/tests/it/uuid.rs [hunk 1]
```diff
@@ -3,10 +3,10 @@ use std::marker::PhantomData;
 
 #[derive(TypeUuidProvider)]
 #[type_uuid(id = "5fb10a22-4ea9-4a13-a58c-82f2734aefd8")]
-struct Foo {}
+struct _Foo {}
 
 #[derive(TypeUuidProvider)]
 #[type_uuid(id = "5fb10a22-4ea9-4a13-a58c-82f2734aefd9")]
-struct Bar<T> {
+struct _Bar<T> {
```
Comment (hamirmahal) [inline fyrox-core-derive/tests/it/uuid.rs:10]: I wasn't sure whether or not to remove `Foo` and `Bar` altogether.

File: fyrox-impl/src/renderer/mod.rs [hunk 2]
```diff
@@ -205,7 +207,8 @@ pub struct QualitySettings {
     /// Spot shadow map precision. Allows you to select compromise between
     /// quality and performance.
     pub spot_shadow_map_precision: ShadowMapPrecision,
-    ///
+    /// Specifies the distance from the camera at which spot shadows start to fade out.
+    /// Shadows beyond this distance will gradually become less visible.
```
Comment (hamirmahal) [inline fyrox-impl/src/renderer/mod.rs:211]: I think the documentation here needs checking.

File: fyrox-impl/src/renderer/mod.rs [hunk 3]
```diff
@@ -190,7 +190,9 @@ pub struct QualitySettings {
     /// Point shadow map precision. Allows you to select compromise between
     /// quality and performance.
     pub point_shadow_map_precision: ShadowMapPrecision,
-    ///
+    /// Point shadows fade out range.
+    /// Specifies the distance from the camera at which point shadows start to fade out.
+    /// Shadows beyond this distance will gradually become less visible.
```
Comment (hamirmahal) [inline fyrox-impl/src/renderer/mod.rs:195]: I think the documentation here needs checking.

File: fyrox-impl/src/utils/lightmap.rs [hunk 4]
```diff
@@ -97,7 +97,7 @@ pub fn apply_surface_data_patch(data: &mut SurfaceData, patch: &SurfaceDataPatch
     }
 }
 
-///
+/// Lightmap entry.
```
Comment (hamirmahal) [inline fyrox-impl/src/utils/lightmap.rs:100]: This might need to be more descriptive.
